service:
  name: game-api-assessment

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  timestamp:
    handler: src/handlers/timestamp.unixTimeMs
    events:
      - http:
          method: get
          path: Timestamp
    memorySize: 128
  transaction:
    handler: src/handlers/user.transactionRecording
    events:
      - http:
          method: post
          path: Transaction
    memorySize: 512
  transactionStats:
    handler: src/handlers/user.transactionStats
    events:
      - http:
          method: post
          path: TransactionStats
    memorySize: 512
