service:
  name: game-api-assessment

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  timestamp:
    handler: src/handlers/timestamp.unixTimeMs
    events:
      - http:
          method: get
          path: Timestamp
    memorySize: 128
  transaction:
    handler: src/handlers/user.transactionRecording
    events:
      - http:
          method: post
          path: Transaction
    memorySize: 512
  transactionStats:
    handler: src/handlers/user.transactionStats
    events:
      - http:
          method: post
          path: TransactionStats
    memorySize: 512
  scorePost:
    handler: src/handlers/leaderboard.createLeaderboardScore
    events:
      - http:
          method: post
          path: ScorePost
    memorySize: 512
  leaderboardGet:
    handler: src/handlers/leaderboard.leaderboardGet
    events:
      - http:
          method: post
          path: LeaderboardGet
    memorySize: 512
  userSave:
    handler: src/handlers/user.userSave
    events:
      - http:
          method: post
          path: UserSave
    memorySize: 512
  userLoad:
    handler: src/handlers/user.userLoad
    events:
      - http:
          method: post
          path: UserLoad
    memorySize: 512

